FROM python:3.11-slim-buster

WORKDIR /app
# Copy only requirements.txt and install dependencies (this layer will be cached)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .



EXPOSE 8000
CMD [ "fastapi", "run", "app.py"]
# CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"]